eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070
spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schoolsDB
    username: postgres
    password: admin123.
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8000/api/v1/students

management:
  tracing:
    sampling:
      probability: 1.0

## docker run
##  --name students-microservice
##  -e POSTGRES_PASSWORD=studentspwd123
##  -e POSTGRES_USER=postgres
##  -e POSTGRES_DB=studentsDB -d
##  -p 5432:5432
##  postgres:alpine