eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/studentsDB
    username: postgres
    password: admin123.
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics


## docker run
##  --name students-microservice
##  -e POSTGRES_PASSWORD=studentspwd123
##  -e POSTGRES_USER=postgres
##  -e POSTGRES_DB=studentsDB -d
##  -p 5432:5432
##  postgres:alpine